// Planning-only interaction. No disk, emulator or persistent storage access.
const cap=document.querySelector('#musicBytes'),count=document.querySelector('#capacityResult');
function capacity(){const m=+cap.value,p=m+871,a=Math.floor((60000-44978)/p),b=Math.floor((60000-1628)/p);count.textContent=`${a+b}ステージ（A面 ${a} ／ B面 ${b}）`;document.querySelector('#capacityDetail').textContent=`音楽 ${m.toLocaleString()} B ＋ 譜面・情報・管理 871 B ＝ ${p.toLocaleString()} B／ステージ`;for(const [s,f,n]of[['A',44978,a],['B',1628,b]]){document.querySelector('#fixed'+s).style.width=f/65500*100+'%';document.querySelector('#songs'+s).style.width=n*p/65500*100+'%';document.querySelector('#usage'+s).textContent=`${(f+n*p).toLocaleString()} / 65,500 B`}}
cap.onchange=capacity;capacity();
let view='title',side='A',track=0,records=false,loaded=new Set(['A']),saveFailed=false;
const box=document.querySelector('#flowScreen'),disk=document.querySelector('#currentSide');
const songName=()=>track===0?'NEON AFTERGLOW':`STAGE ${String(track+1).padStart(2,'0')}（収録枠）`;
const wanted=()=>track<3?'A':'B';
function draw(){disk.textContent='現在の面：'+side+'（想定）';let s='';
if(view==='title')s='<div class="screen-label">TITLE</div><h3>NEON CHAIN</h3><p>タイトル画面</p><button data-act="start">START → 曲選択</button>';
if(view==='select')s='<div class="screen-label">SONG SELECT / '+(records?'RECORDS':'PLAY')+'</div><div class="demo-buttons"><button data-act="tab">'+(records?'選択に切替':'ハイスコア閲覧')+'</button><button data-act="title">タイトルへ</button></div><label>曲 <select id="demoTrack">'+Array.from({length:16},(_,i)=>'<option value="'+i+'" '+(i===track?'selected':'')+'>'+(i+1)+' · '+(i<3?'A':'B')+'面 · '+(i===0?'NEON AFTERGLOW':'収録枠')+'</option>').join('')+'</select></label><h3>'+songName()+'</h3><p>'+wanted()+'面 ／ EASY・HARD ／ 通常・RANDOM</p>'+(records?'<p>自己ベスト：'+(loaded.has(wanted())?'—（表示例・実記録なし）':'未読。'+wanted()+'面の読み込みが必要')+'</p>'+(!loaded.has(wanted())?'<button data-act="read">この面の記録を読む</button>':''):'<button data-act="choose">この曲を選択</button>');
if(view==='swap')s='<div class="screen-label">DISK CHANGE</div><h3>'+wanted()+'面を入れてください</h3><p>面と曲パックを確認してから読み込みます。</p><button data-act="insert">'+wanted()+'面に切替（デモ）</button> <button data-act="cancel">キャンセル</button>';
if(view==='playing')s='<div class="screen-label">PLAY / 操作説明用</div><h3>'+songName()+'</h3><p>ここではゲームを実行しません。演奏中はディスクへアクセスしない設計です。</p><button data-act="clear">クリアした想定で進む</button>';
if(view==='save')s='<div class="screen-label">RESULT / SAVE</div><h3>新記録を保存（想定）</h3><p>'+side+'面末尾のSCORE_'+side+'へ書き込み、読み戻しを確認します。</p><div class="demo-buttons"><button data-act="saved">保存成功を試す</button><button data-act="fail">保存失敗を試す</button></div>';
if(view==='error')s='<div class="screen-label">SAVE ERROR / 想定</div><h3>保存できませんでした</h3><p>RAM上の新記録は保持。再試行か、保存せず進むかを選びます。</p><button data-act="retry">再試行</button> <button data-act="skip">保存せず続ける</button>';
if(view==='result')s='<div class="screen-label">RESULT</div><h3>'+songName()+'</h3><p>'+(saveFailed?'未保存（想定）':'保存済み（想定）')+'</p><div class="demo-buttons"><button data-act="menu">曲選択へ</button><button data-act="replay">もう一度プレイ</button></div><p>再プレイは曲と設定を保持し、RAMにある曲を再利用します。</p>';
box.innerHTML=s;const sel=document.querySelector('#demoTrack');if(sel)sel.onchange=e=>{track=+e.target.value;draw()};}
box.onclick=e=>{const a=e.target.closest('[data-act]')?.dataset.act;if(!a)return;switch(a){case'title':view='title';break;case'start':case'menu':view='select';records=false;break;case'tab':records=!records;break;case'choose':view=side===wanted()?'playing':'swap';break;case'read':view='swap';break;case'insert':side=wanted();loaded.add(side);view=records?'select':'playing';break;case'cancel':view='select';break;case'clear':view='save';saveFailed=false;break;case'fail':view='error';break;case'retry':view='save';break;case'skip':saveFailed=true;view='result';break;case'saved':saveFailed=false;view='result';break;case'replay':view='playing';break}draw()};draw();
