; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Redline Mirage:
; FAMISTUDIO_USE_VOLUME_TRACK = 1

.export _music_data_redline_mirage:=music_data_redline_mirage

music_data_redline_mirage:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Redline Mirage
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 0, 0

.export music_data_redline_mirage
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env10,@env6,@env7,@env0 ; 00 : Hat
	.word @env4,@env6,@env7,@env0 ; 01 : Clap
	.word @env1,@env6,@env7,@env0 ; 02 : Kick
	.word @env3,@env6,@env9,@env0 ; 03 : Answer
	.word @env2,@env6,@env8,@env0 ; 04 : Brass
	.word @env11,@env6,@env8,@env0 ; 05 : Tail
	.word @env1,@env6,@env8,@env0 ; 06 : Stab
	.word @env5,@env6,@env7,@env0 ; 07 : Bass

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$cc,$c8,$c4,$c1,$c0,$00,$06
@env2:
	.byte $00,$cf,$ce,$cd,$cc,$cb,$ca,$ca,$c9,$c9,$c8,$c8,$c7,$00,$0c
@env3:
	.byte $00,$cc,$cc,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$00,$0c
@env4:
	.byte $00,$cf,$ca,$cc,$c8,$c6,$c4,$c2,$c1,$c0,$00,$09
@env5:
	.byte $00,$cf,$7f,$00,$02
@env6:
	.byte $c0,$7f,$00,$01
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $c2,$7f,$00,$00
@env9:
	.byte $c1,$7f,$00,$00
@env10:
	.byte $00,$c9,$c5,$c2,$c0,$00,$04
@env11:
	.byte $00,$cc,$05,$cb,$05,$ca,$05,$c9,$05,$c8,$05,$c7,$05,$c6,$05,$c5,$05,$c4,$05,$c3,$05,$c2,$05,$c1,$05,$c0,$00,$19

@samples:

@tempo_env_1_mid:
	.byte $03,$05,$80

@song0ch0:
	.byte $ff, $bf, $48, $75, $86, $2b, $95, $00, $95, $2e, $95, $00, $95, $32, $95, $00, $95, $37, $95, $00, $95, $48, $76, $2b
	.byte $95, $00, $95, $2e, $95, $00, $95, $32, $95, $00, $95, $37, $95, $00, $95, $48, $77, $2b, $95, $00, $95, $2e, $95, $00
	.byte $95, $32, $95, $00, $95, $37, $95, $00, $95, $48, $7a
@song0ref60:
	.byte $88
@song0ref61:
	.byte $37, $95, $3a, $95, $39, $89, $37, $a1, $35, $95, $37, $95, $32, $95, $35, $95, $48, $37, $a1, $35, $89, $33, $ad, $32
	.byte $95, $33, $95, $37, $ad, $48, $39, $95, $3c, $95, $3a, $95, $39, $95, $35, $a1, $37, $89, $39, $ad, $48, $39, $a1, $37
	.byte $89, $36, $ad, $32, $95, $36, $95, $39, $95, $36, $95, $48, $37, $95, $3a, $95, $3e, $a1, $3c, $89, $3a, $95, $39, $95
	.byte $37, $ad, $48, $37, $95, $35, $95, $33, $a1, $32, $89, $33, $95, $37, $95, $3a, $ad, $48, $3c, $a1, $3a, $89, $39, $95
	.byte $37, $95, $35, $95, $37, $95, $39, $95, $3c, $95, $48, $39, $95, $37, $95, $36, $95, $32, $95, $36, $95, $39, $95, $36
	.byte $95, $00, $95, $48, $78, $86
@song0ref187:
	.byte $3e, $a1, $00, $89, $3a, $95, $00, $89, $37, $89, $3a, $a1, $00, $89, $3e, $95, $00, $95, $48, $3a, $a1, $00, $89, $37
	.byte $95, $00, $89, $33, $89, $37, $a1, $00, $89, $3a, $95, $00, $95, $48, $3c, $a1, $00, $89, $39, $95, $00, $89, $35, $89
	.byte $39, $a1, $00, $89, $3c, $95, $00, $95, $48, $36, $a1, $00, $89, $32, $95, $00, $95, $36, $95, $39, $95, $36, $95, $00
	.byte $95, $48
	.byte $41, $46
	.word @song0ref187
	.byte $48
	.byte $41, $46
	.word @song0ref187
	.byte $48
	.byte $41, $46
	.word @song0ref187
	.byte $48, $88
@song0ref274:
	.byte $37, $95, $3a, $95, $3e, $95, $3a, $95, $37, $95, $3a, $95, $3e, $95, $3e, $95, $48, $33, $95, $37, $95, $3a, $95, $37
	.byte $95, $33, $95, $37, $95, $3a, $95, $3a, $95, $48, $35, $95, $39, $95, $3c, $95, $39, $95, $35, $95, $39, $95, $3c, $95
	.byte $3c, $95, $48, $79, $32, $95, $36, $95, $39, $95, $36, $95, $32, $95, $36, $95, $39, $95, $39, $95, $48
	.byte $41, $20
	.word @song0ref274
	.byte $48, $7a, $35, $95, $39, $95, $3c, $95, $39, $95, $35, $95, $39, $95, $3c, $95, $3c, $95, $48, $32, $95, $36, $95, $39
	.byte $95, $36, $95, $32, $95, $36, $95, $00, $ad, $48
	.byte $41, $74
	.word @song0ref61
	.byte $48
	.byte $41, $74
	.word @song0ref61
	.byte $48, $77, $86, $37, $c5, $00, $95, $3e, $ad, $00, $ad, $48, $33, $c5, $00, $95, $3a, $ad, $00, $ad, $48, $35, $c5, $00
	.byte $95, $3c, $ad, $00, $ad, $48, $32, $c5, $00, $95, $39, $ad, $00, $ad, $48, $7b
	.byte $41, $74
	.word @song0ref60
	.byte $48
	.byte $41, $74
	.word @song0ref61
	.byte $48, $7c, $37, $95, $3a, $95, $39, $89, $37, $a1, $35, $95, $37, $95, $32, $95, $35, $95, $48, $7b, $37, $a1, $35, $89
	.byte $33, $ad, $32, $95, $33, $95, $37, $ad, $48, $7a, $39, $95, $3c, $95, $3a, $95, $39, $95, $35, $a1, $37, $89, $39, $ad
	.byte $48, $79, $39, $a1, $37, $89, $36, $ad, $32, $95, $36, $95, $39, $95, $36, $95, $48, $78, $37, $95, $3a, $95, $3e, $a1
	.byte $3c, $89, $3a, $95, $39, $95, $37, $ad, $48, $77, $37, $95, $35, $95, $33, $a1, $32, $89, $33, $95, $37, $95, $3a, $ad
	.byte $48, $76, $3c, $a1, $3a, $89, $39, $95, $37, $95, $35, $95, $37, $95, $39, $95, $3c, $95, $48, $79, $8a, $37, $ff, $8d
	.byte $00, $ad, $44, $00
@song0ch1:
	.byte $74, $8c
@song0ref561:
	.byte $2b, $83, $00, $2e, $83, $00, $32, $83, $00, $c7, $2b, $83, $00, $2e, $83, $00, $32, $83, $00, $c7, $27, $83, $00, $2b
	.byte $83, $00, $2e, $83, $00, $c7, $27, $83, $00, $2b, $83, $00, $2e, $83, $00, $c7, $29, $83, $00, $2d, $83, $00, $30, $83
	.byte $00, $c7, $29, $83, $00, $2d, $83, $00, $30, $83, $00, $c7, $26, $83, $00, $2a, $83, $00, $2d, $83, $00, $c7, $26, $83
	.byte $00, $2a, $83, $00, $2d, $83, $00, $c7, $97, $76, $37, $83, $00, $3a, $83, $00, $3e
@song0ref650:
	.byte $83, $00
@song0ref652:
	.byte $97, $37, $83, $00, $3a, $83, $00, $3e, $83, $00, $97, $37, $83, $00, $3a, $83, $00, $3e, $83, $00, $97
@song0ref673:
	.byte $37, $83, $00, $3a, $83, $00, $3e, $83, $00, $97, $33, $83, $00, $37, $83, $00, $3a, $83, $00, $97, $33, $83, $00, $37
	.byte $83, $00, $3a, $83, $00, $97, $33, $83, $00, $37, $83, $00, $3a, $83, $00, $97, $33, $83, $00, $37, $83, $00, $3a, $83
	.byte $00, $97, $35, $83, $00, $39, $83, $00, $3c, $83, $00, $97, $35, $83, $00, $39, $83, $00, $3c, $83, $00, $97, $35, $83
	.byte $00, $39, $83, $00, $3c, $83, $00, $97, $35, $83, $00, $39, $83, $00, $3c, $83, $00, $97, $32, $83, $00, $36, $83, $00
	.byte $39, $83, $00, $97, $32, $83, $00, $36, $83, $00, $39, $83, $00, $97, $32, $83, $00, $36, $83, $00, $39, $83, $00, $97
	.byte $32, $83, $00, $36, $83, $00, $39
	.byte $41, $21
	.word @song0ref650
	.byte $41, $7f
	.word @song0ref673
@song0ref806:
	.byte $83, $00, $97, $2b, $83, $00, $2e, $83, $00, $32, $83, $00, $97, $2b, $83, $00, $2e, $83, $00, $32, $83, $00, $97, $2b
	.byte $83, $00, $2e, $83, $00, $32, $83, $00, $97, $2b, $83, $00, $2e, $83, $00, $32, $83, $00, $97, $27, $83, $00, $2b, $83
	.byte $00, $2e, $83, $00, $97, $27, $83, $00, $2b, $83, $00, $2e, $83, $00, $97, $27, $83, $00, $2b, $83, $00, $2e, $83, $00
	.byte $97, $27, $83, $00, $2b, $83, $00, $2e, $83, $00, $97, $29, $83, $00, $2d, $83, $00, $30, $83, $00, $97, $29, $83, $00
	.byte $2d, $83, $00, $30, $83, $00, $97, $29, $83, $00, $2d, $83, $00, $30, $83, $00, $97, $29, $83, $00, $2d, $83, $00, $30
	.byte $83, $00, $97, $26, $83, $00, $2a, $83, $00, $2d, $83, $00, $97, $26, $83, $00, $2a, $83, $00, $2d, $83, $00, $97, $26
	.byte $83, $00, $2a, $83, $00, $2d, $83, $00, $97, $26, $83, $00, $2a, $83, $00, $2d
	.byte $41, $a0
	.word @song0ref806
	.byte $41, $a0
	.word @song0ref806
	.byte $41, $a0
	.word @song0ref806
	.byte $41, $a0
	.word @song0ref806
	.byte $41, $98
	.word @song0ref806
	.byte $af
	.byte $41, $1f
	.word @song0ref652
	.byte $41, $7f
	.word @song0ref673
	.byte $41, $21
	.word @song0ref650
	.byte $41, $7f
	.word @song0ref673
	.byte $41, $21
	.word @song0ref650
	.byte $41, $7f
	.word @song0ref673
	.byte $41, $21
	.word @song0ref650
	.byte $41, $7f
	.word @song0ref673
	.byte $83, $00, $74
	.byte $41, $ee
	.word @song0ref561
	.byte $41, $21
	.word @song0ref650
	.byte $41, $7f
	.word @song0ref673
	.byte $41, $21
	.word @song0ref650
	.byte $41, $7f
	.word @song0ref673
	.byte $41, $21
	.word @song0ref650
	.byte $41, $7f
	.word @song0ref673
	.byte $41, $a0
	.word @song0ref806
	.byte $41, $7a
	.word @song0ref806
	.byte $75, $2b, $95, $2e, $95, $32, $95, $37, $95, $00, $dd, $44, $00
@song0ch2:
	.byte $8e, $13, $ff, $8d, $00, $ad, $0f, $ff, $8d, $00, $ad, $25, $19, $11, $85, $11, $87, $00, $1d, $87, $00, $18
@song0ref1072:
	.byte $87, $00, $25, $19, $11, $85, $11, $87, $00, $1d, $87, $00, $18, $87, $00, $25, $19, $11, $85, $11, $87, $00, $1d, $87
	.byte $00, $18, $87, $00, $25, $19
@song0ref1102:
	.byte $11, $85, $11, $87, $00, $1d, $87, $00, $18, $87, $00, $25, $19, $0e, $85, $0e, $87, $00, $1a, $87, $00, $15, $87, $00
	.byte $25, $19, $0e, $85, $0e, $87, $00, $1a, $87, $00, $15, $87, $00, $25, $19, $0e, $85, $0e, $87, $00, $1a, $87, $00, $15
	.byte $87, $00, $25, $19, $0e, $85, $0e, $87, $00, $1a, $87, $00, $15, $87, $00
@song0ref1165:
	.byte $25, $19, $13, $85, $13, $87, $00, $1f, $87, $00, $1a, $87, $00, $25, $19, $13, $85, $13, $87, $00, $1f, $87, $00, $1a
	.byte $87, $00, $25, $19, $13, $85, $13, $87, $00, $1f, $87, $00, $1a, $87, $00, $25, $19, $13, $85, $13, $87, $00, $1f, $87
	.byte $00, $1a, $87, $00, $25, $19, $0f, $85, $0f, $87, $00, $1b, $87, $00, $16, $87, $00, $25, $19, $0f, $85, $0f, $87, $00
	.byte $1b, $87, $00, $16, $87, $00, $25, $19, $0f, $85, $0f, $87, $00, $1b, $87, $00, $16, $87, $00, $25, $19, $0f, $85, $0f
	.byte $87, $00, $1b, $87, $00, $16
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $39
	.word @song0ref1102
	.byte $97
	.byte $41, $66
	.word @song0ref1165
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $3f
	.word @song0ref1102
	.byte $13, $ff, $8d, $00, $ad, $0f, $ff, $8d, $00, $ad, $11, $ff, $8d, $00, $ad, $0e, $ff, $8d, $00, $ad
	.byte $41, $66
	.word @song0ref1165
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $41, $a5
	.word @song0ref1102
	.byte $41, $2b
	.word @song0ref1072
	.byte $11, $85, $11, $87, $00, $1d, $87, $00, $18, $87, $00, $13, $ff, $8d, $00, $ad, $44, $00
@song0ch3:
	.byte $ff, $bf, $ff, $bf
@song0ref1422:
	.byte $7b
@song0ref1423:
	.byte $84, $40, $04, $89, $00, $89, $75, $80, $03, $89, $00, $89, $7c, $82, $40, $09, $89, $00, $89, $75, $80, $03, $89, $00
	.byte $89, $7b, $84, $40, $04, $89, $00, $89, $75, $80, $03, $89, $00, $89, $7c, $82, $40, $09, $89, $00, $89, $75, $80, $03
	.byte $89, $00, $89
@song0ref1474:
	.byte $82, $40, $09, $89, $02, $89, $76, $40, $09, $89, $02, $89, $77, $40, $09, $89, $02, $89, $78, $40, $09, $89, $02, $89
	.byte $79, $40, $09, $89, $02, $89, $7a, $40, $09, $89, $02, $89, $7b, $40, $09, $89, $02, $89, $00, $95
	.byte $41, $20
	.word @song0ref1423
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
@song0ref1527:
	.byte $7b, $84, $40, $04, $89, $00, $89, $75, $80, $03, $89, $00, $89, $7c, $82, $40, $09, $89, $00, $89, $75, $80, $03, $89
	.byte $00, $89, $7b, $84, $40, $04, $89, $00, $89, $75, $80, $03, $89, $00, $89, $7c, $82, $40, $09, $89, $78, $40, $0b, $89
	.byte $75, $80, $03, $89, $78, $82, $40, $0b, $89
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1527
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1527
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1527
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $3e
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1423
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1527
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1527
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $af, $73, $03, $89, $00, $d1, $03, $89, $00, $a1, $af, $03, $89, $00, $d1, $03, $89, $00, $a1, $af, $03, $89, $00, $d1
	.byte $03, $89, $00, $a1, $75
	.byte $41, $1e
	.word @song0ref1474
	.byte $41, $20
	.word @song0ref1423
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1527
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1527
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $41, $20
	.word @song0ref1422
	.byte $7a, $84, $40, $04, $89, $00, $ff, $b1, $44, $00
@song0ch4:
@song0ref1825:
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
	.byte $ff, $bf, $ff, $bf, $ff, $bf
	.byte $41, $1e
	.word @song0ref1825
	.byte $41, $1e
	.word @song0ref1825
	.byte $41, $1e
	.word @song0ref1825
	.byte $41, $1e
	.word @song0ref1825
	.byte $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $44, $00
